version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 1 * * *"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 3
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-actions-non-major:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
