name: Tests
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  bootstrap:
    name: Bootstrap tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - name: Install test dependencies
        run: |
          nix profile install nixpkgs#chezmoi nixpkgs#jq
      - name: Run tests
        run: bash tests/run.sh
